### ISSUE TITLE
ALL FILES 

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.id-id#1]
All files in image folder are untranslated yet
To use active sentence form, not imperative form, especially in the header and sub-header.
To recheck whether the apps/software is already translated/localized as well. If it's not translated, please use the English instead.
To recheck and assess whether it's a programming language and string that should not be translated. Please translate if it's not a programming language. Please rereview the instruction and guideline to differentiate the same.
If unsure, it's safely to leave in English. However, if it's preferred to do so, please make sure everything is treated the same.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The locfile with Blocked status, I re-set Prehandoff, waiting for check In.[ ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9BWi0yMDQ8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7SW5kb25lc2lhbiAoSW5kb25lc2lhKTwvUVI%2bPFFSIElkPSI1IiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0NvbnRhaW5zOy9JbnN0cnVjdGlvbnMvTGFicy9tZWRpYS88L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)

**Comment by chriscarty00** [comment]
Project LAB-AZ-204.master no longer has Id-id as a language 
![image](https://user-images.githubusercontent.com/63402128/205053393-93868868-c0de-4cf8-9ea1-67d19f28b9f1.png)

**Comment by chriscarty00** [comment]
Indonesian had been added back and now all the art files are localized [Query](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQ29udGVudCBHcm91cDtFcXVhbDtMQUJfQVotMjA0X21hc3RlcjwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtJbmRvbmVzaWFuIChJbmRvbmVzaWEpPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)
